#' Generate QC metrics and plots for TDHIA beta matrices
#'
#' @description
#' Builds a simple quality-control report for beta matrices generated by the
#' TDHIA processing workflow. The function is intended to be run after the data
#' have been imported and at least the initial probe filtering has been applied.
#'
#' The default `level = "cpg"` uses `data_beta$cpg_beta$cpg_beta_df`, which is
#' usually the most useful matrix for downstream analysis QC. Probe-level and
#' ICR-level reports can also be generated when those objects are present in the
#' pipeline output.
#'
#' @param data_beta Named list returned by `tdhia_pipeline()` or by the stepwise
#' TDHIA workflow. Expected to contain one of:
#' `filt_probe_beta$probe_beta_df`, `cpg_beta$cpg_beta_df`, or
#' `icr_beta$icr_beta_df`, depending on `level`.
#' @param output_dir_path Directory where the `QC` subdirectory should be
#' created. Defaults to the current working directory.
#' @param level Which matrix to summarize: `"cpg"` (default), `"probe"`, or
#' `"icr"`.
#' @param show_plots Logical. If `TRUE`, draw plots in the active graphics
#' device, such as the RStudio Plots pane. Defaults to `interactive()`.
#' @param save_pdf Logical. If `TRUE`, save all QC plots to a PDF file in the
#' QC directory.
#' @param save_metrics Logical. If `TRUE`, save sample-level and feature-level
#' QC metrics as CSV files in the QC directory.
#' @param max_density_samples Integer maximum number of samples to overlay in
#' the beta-density plot. This keeps dense studies readable. Samples are taken
#' from the first columns after filtering all-empty samples.
#' @param detection_pvalue_threshold Numeric detection p-value threshold used
#' for optional detection p-value QC when `probe_pval_df` is available.
#' @param outlier_z_threshold Numeric absolute z-score threshold used for simple
#' sample outlier flags based on missingness, mean beta, SD beta, and mean sample
#' correlation.
#' @param verbose Logical. If `TRUE`, print progress and output locations.
#'
#' @return A list with:
#' \itemize{
#'   \item `sample_metrics`: sample-level NA fraction, mean beta, and SD beta.
#'   \item `feature_metrics`: feature-level NA fraction.
#'   \item `sample_outliers`: simple sample outlier flags.
#'   \item `detection_qc`: detection p-value QC tables when available.
#'   \item `retention_summary`: counts retained at probe, CpG, ICR, and sample levels.
#'   \item `design_score_qc`: design score retention summary when available.
#'   \item `icr_coverage_qc`: ICR coverage summary when available.
#'   \item `replicate_probe_qc`: replicate probe agreement summary when available.
#'   \item `matrix_dimensions`: dimensions of the selected beta matrix.
#'   \item `beta_range`: observed beta range.
#'   \item `qc_dir`: output QC directory.
#'   \item `metrics_paths`: CSV paths when `save_metrics = TRUE`.
#'   \item `plots_path`: PDF path when `save_pdf = TRUE`.
#' }
#'
#' @importFrom grDevices dev.off pdf
#' @importFrom stats cor density median prcomp sd
#' @importFrom utils write.csv
#' @export
#'
#' @examples
#' \dontrun{
#' data_beta <- tdhia_pipeline(idat_dir_paths = "path/to/idats")
#' qc <- tdhia_qc_report(
#'   data_beta,
#'   output_dir_path = "results",
#'   level = "cpg"
#' )
#' }
tdhia_qc_report <- function(data_beta,
                            output_dir_path = getwd(),
                            level = c("cpg", "probe", "icr"),
                            show_plots = interactive(),
                            save_pdf = TRUE,
                            save_metrics = TRUE,
                            max_density_samples = 50,
                            detection_pvalue_threshold = 0.2,
                            outlier_z_threshold = 3,
                            verbose = TRUE) {
  level <- match.arg(level)

  beta <- get_qc_beta_matrix(data_beta, level = level)
  beta_m <- as.matrix(beta)
  storage.mode(beta_m) <- "numeric"

  if (is.null(rownames(beta_m))) {
    rownames(beta_m) <- paste0(level, "_", seq_len(nrow(beta_m)))
  }
  if (is.null(colnames(beta_m))) {
    colnames(beta_m) <- paste0("sample_", seq_len(ncol(beta_m)))
  }

  qc_dir <- file.path(output_dir_path, "QC")
  dir.create(qc_dir, recursive = TRUE, showWarnings = FALSE)

  sample_metrics <- data.frame(
    Sample = colnames(beta_m),
    NA_fraction = colMeans(is.na(beta_m)),
    Mean_beta = colMeans(beta_m, na.rm = TRUE),
    SD_beta = apply(beta_m, 2, stats::sd, na.rm = TRUE),
    row.names = NULL
  )

  feature_label <- switch(
    level,
    probe = "Probe",
    cpg = "CpG",
    icr = "ICR"
  )
  feature_metrics <- data.frame(
    Feature = rownames(beta_m),
    NA_fraction = rowMeans(is.na(beta_m)),
    row.names = NULL
  )
  names(feature_metrics)[1] <- feature_label

  plot_matrix <- prepare_qc_plot_matrix(beta_m)
  sample_outliers <- build_sample_outlier_qc(
    sample_metrics = sample_metrics,
    plot_matrix = plot_matrix,
    z_threshold = outlier_z_threshold
  )
  detection_qc <- build_detection_pvalue_qc(
    data_beta = data_beta,
    threshold = detection_pvalue_threshold
  )
  retention_summary <- build_retention_summary(data_beta = data_beta)
  design_score_qc <- build_design_score_qc(data_beta = data_beta)
  icr_coverage_qc <- build_icr_coverage_qc(data_beta = data_beta)
  replicate_probe_qc <- build_replicate_probe_qc(data_beta = data_beta)

  metrics_paths <- list()
  if (save_metrics) {
    metrics_paths$sample_metrics <- file.path(qc_dir, paste0("sample_QC_metrics_", level, ".csv"))
    metrics_paths$feature_metrics <- file.path(qc_dir, paste0("feature_QC_metrics_", level, ".csv"))
    metrics_paths$sample_outliers <- file.path(qc_dir, paste0("sample_outlier_flags_", level, ".csv"))
    metrics_paths$retention_summary <- file.path(qc_dir, "retention_summary.csv")
    utils::write.csv(sample_metrics, file = metrics_paths$sample_metrics, row.names = FALSE)
    utils::write.csv(feature_metrics, file = metrics_paths$feature_metrics, row.names = FALSE)
    utils::write.csv(sample_outliers, file = metrics_paths$sample_outliers, row.names = FALSE)
    utils::write.csv(retention_summary, file = metrics_paths$retention_summary, row.names = FALSE)

    if (!is.null(detection_qc)) {
      metrics_paths$detection_sample_metrics <- file.path(qc_dir, "detection_sample_QC_metrics.csv")
      metrics_paths$detection_probe_metrics <- file.path(qc_dir, "detection_probe_QC_metrics.csv")
      utils::write.csv(detection_qc$sample_metrics, file = metrics_paths$detection_sample_metrics, row.names = FALSE)
      utils::write.csv(detection_qc$probe_metrics, file = metrics_paths$detection_probe_metrics, row.names = FALSE)
    }

    if (!is.null(design_score_qc)) {
      metrics_paths$design_score_metrics <- file.path(qc_dir, "design_score_QC_metrics.csv")
      utils::write.csv(design_score_qc, file = metrics_paths$design_score_metrics, row.names = FALSE)
    }

    if (!is.null(icr_coverage_qc)) {
      metrics_paths$icr_coverage_metrics <- file.path(qc_dir, "icr_coverage_QC_metrics.csv")
      utils::write.csv(icr_coverage_qc, file = metrics_paths$icr_coverage_metrics, row.names = FALSE)
    }

    if (!is.null(replicate_probe_qc)) {
      metrics_paths$replicate_probe_metrics <- file.path(qc_dir, "replicate_probe_QC_metrics.csv")
      utils::write.csv(replicate_probe_qc, file = metrics_paths$replicate_probe_metrics, row.names = FALSE)
    }
  }

  plots_path <- NULL

  if (show_plots) {
    draw_tdhia_qc_plots(
      beta_m = beta_m,
      plot_matrix = plot_matrix,
      level = level,
      sample_metrics = sample_metrics,
      feature_metrics = feature_metrics,
      max_density_samples = max_density_samples,
      sample_outliers = sample_outliers,
      detection_qc = detection_qc,
      retention_summary = retention_summary,
      design_score_qc = design_score_qc,
      icr_coverage_qc = icr_coverage_qc,
      replicate_probe_qc = replicate_probe_qc
    )
  }

  if (save_pdf) {
    plots_path <- file.path(qc_dir, paste0("QC_plots_", level, ".pdf"))
    grDevices::pdf(plots_path, width = 10, height = 8)
    tryCatch(
      draw_tdhia_qc_plots(
        beta_m = beta_m,
        plot_matrix = plot_matrix,
        level = level,
        sample_metrics = sample_metrics,
        feature_metrics = feature_metrics,
        max_density_samples = max_density_samples,
        sample_outliers = sample_outliers,
        detection_qc = detection_qc,
        retention_summary = retention_summary,
        design_score_qc = design_score_qc,
        icr_coverage_qc = icr_coverage_qc,
        replicate_probe_qc = replicate_probe_qc
      ),
      finally = grDevices::dev.off()
    )
  }

  if (verbose) {
    cat("TDHIA QC report complete.\n")
    cat("Level:", level, "\n")
    cat("QC directory:", qc_dir, "\n")
    if (!is.null(plots_path)) cat("QC plots:", plots_path, "\n")
  }

  list(
    sample_metrics = sample_metrics,
    feature_metrics = feature_metrics,
    sample_outliers = sample_outliers,
    detection_qc = detection_qc,
    retention_summary = retention_summary,
    design_score_qc = design_score_qc,
    icr_coverage_qc = icr_coverage_qc,
    replicate_probe_qc = replicate_probe_qc,
    matrix_dimensions = dim(beta_m),
    beta_range = range(beta_m, na.rm = TRUE),
    qc_dir = qc_dir,
    metrics_paths = metrics_paths,
    plots_path = plots_path
  )
}

get_qc_beta_matrix <- function(data_beta, level) {
  if (!is.list(data_beta)) {
    stop("`data_beta` must be a named list returned by tdhia_pipeline() or the stepwise TDHIA workflow.")
  }

  beta <- switch(
    level,
    probe = data_beta$filt_probe_beta$probe_beta_df,
    cpg = data_beta$cpg_beta$cpg_beta_df,
    icr = data_beta$icr_beta$icr_beta_df
  )

  if (is.null(beta)) {
    stop(sprintf(
      "Could not find a %s-level beta matrix in `data_beta`. Expected %s.",
      level,
      switch(
        level,
        probe = "`data_beta$filt_probe_beta$probe_beta_df`",
        cpg = "`data_beta$cpg_beta$cpg_beta_df`",
        icr = "`data_beta$icr_beta$icr_beta_df`"
      )
    ))
  }

  if (!is.matrix(beta) && !is.data.frame(beta)) {
    stop("The selected beta object must be a matrix or data frame.")
  }

  if (nrow(beta) == 0 || ncol(beta) == 0) {
    stop("The selected beta matrix has zero rows or zero columns.")
  }

  beta
}

prepare_qc_plot_matrix <- function(beta_m) {
  keep_rows <- rowSums(!is.na(beta_m)) > 0
  keep_cols <- colSums(!is.na(beta_m)) > 0
  plot_matrix <- beta_m[keep_rows, keep_cols, drop = FALSE]

  if (nrow(plot_matrix) == 0 || ncol(plot_matrix) == 0) {
    return(plot_matrix)
  }

  row_medians <- apply(plot_matrix, 1, stats::median, na.rm = TRUE)
  row_medians[is.na(row_medians)] <- 0.5
  missing_index <- which(is.na(plot_matrix), arr.ind = TRUE)
  if (nrow(missing_index) > 0) {
    plot_matrix[missing_index] <- row_medians[missing_index[, "row"]]
  }

  plot_matrix
}

build_sample_outlier_qc <- function(sample_metrics, plot_matrix, z_threshold) {
  sample_outliers <- sample_metrics
  sample_outliers$Mean_sample_correlation <- NA_real_

  if (ncol(plot_matrix) > 1) {
    cor_mat <- stats::cor(plot_matrix, use = "pairwise.complete.obs")
    diag(cor_mat) <- NA_real_
    mean_cor <- rowMeans(cor_mat, na.rm = TRUE)
    sample_outliers$Mean_sample_correlation[
      match(names(mean_cor), sample_outliers$Sample)
    ] <- mean_cor
  }

  sample_outliers$High_NA_fraction <- abs_z_flag(sample_outliers$NA_fraction, z_threshold)
  sample_outliers$Extreme_mean_beta <- abs_z_flag(sample_outliers$Mean_beta, z_threshold)
  sample_outliers$Extreme_sd_beta <- abs_z_flag(sample_outliers$SD_beta, z_threshold)
  sample_outliers$Low_mean_sample_correlation <- lower_tail_z_flag(
    sample_outliers$Mean_sample_correlation,
    z_threshold
  )
  sample_outliers$Any_outlier_flag <- sample_outliers$High_NA_fraction |
    sample_outliers$Extreme_mean_beta |
    sample_outliers$Extreme_sd_beta |
    sample_outliers$Low_mean_sample_correlation

  sample_outliers
}

build_detection_pvalue_qc <- function(data_beta, threshold) {
  probe_pval <- data_beta$probe_beta$probe_pval_df
  if (is.null(probe_pval)) probe_pval <- data_beta$filt_probe_beta$probe_pval_df
  if (is.null(probe_pval)) return(NULL)

  pval_m <- as.matrix(probe_pval)
  storage.mode(pval_m) <- "numeric"
  if (is.null(rownames(pval_m))) rownames(pval_m) <- paste0("probe_", seq_len(nrow(pval_m)))
  if (is.null(colnames(pval_m))) colnames(pval_m) <- paste0("sample_", seq_len(ncol(pval_m)))

  fail_m <- pval_m > threshold
  sample_metrics <- data.frame(
    Sample = colnames(pval_m),
    Detection_pvalue_NA_fraction = colMeans(is.na(pval_m)),
    Detection_fail_fraction = colMeans(fail_m, na.rm = TRUE),
    Median_detection_pvalue = apply(pval_m, 2, stats::median, na.rm = TRUE),
    row.names = NULL
  )
  probe_metrics <- data.frame(
    Probe = rownames(pval_m),
    Detection_pvalue_NA_fraction = rowMeans(is.na(pval_m)),
    Detection_fail_fraction = rowMeans(fail_m, na.rm = TRUE),
    Median_detection_pvalue = apply(pval_m, 1, stats::median, na.rm = TRUE),
    row.names = NULL
  )

  list(
    threshold = threshold,
    sample_metrics = sample_metrics,
    probe_metrics = probe_metrics,
    pvalue_matrix = pval_m
  )
}

build_retention_summary <- function(data_beta) {
  raw_probe <- data_beta$probe_beta$probe_beta_df
  filt_probe <- data_beta$filt_probe_beta$probe_beta_df
  cpg <- data_beta$cpg_beta$cpg_beta_df
  icr <- data_beta$icr_beta$icr_beta_df

  data.frame(
    Matrix = c("raw_probe", "filtered_probe", "cpg", "icr"),
    Features = c(nrow_or_na(raw_probe), nrow_or_na(filt_probe), nrow_or_na(cpg), nrow_or_na(icr)),
    Samples = c(ncol_or_na(raw_probe), ncol_or_na(filt_probe), ncol_or_na(cpg), ncol_or_na(icr)),
    row.names = NULL
  )
}

build_design_score_qc <- function(data_beta) {
  manifest <- data_beta$probe_beta$manifest
  if (is.null(manifest)) manifest <- data_beta$filt_probe_beta$manifest
  if (is.null(manifest) &&
      requireNamespace("tdhia", quietly = TRUE) &&
      exists("manifest_v1A2_design_scores", envir = asNamespace("tdhia"))) {
    manifest <- get("manifest_v1A2_design_scores", envir = asNamespace("tdhia"))
  }
  if (is.null(manifest) || !"Design.Score" %in% colnames(manifest)) return(NULL)

  probe_id_col <- if ("Probe_ID" %in% colnames(manifest)) "Probe_ID" else if ("Name" %in% colnames(manifest)) "Name" else NULL
  if (is.null(probe_id_col)) return(NULL)

  retained_probes <- rownames(data_beta$filt_probe_beta$probe_beta_df)
  if (is.null(retained_probes)) return(NULL)
  retained_keys <- unique(strip_probe_suffix(retained_probes))

  design_qc <- data.frame(
    Probe = manifest[[probe_id_col]],
    Design.Score = manifest[["Design.Score"]],
    Retained = strip_probe_suffix(manifest[[probe_id_col]]) %in% retained_keys,
    row.names = NULL
  )
  design_qc <- design_qc[!is.na(design_qc$Design.Score), , drop = FALSE]
  design_qc
}

build_icr_coverage_qc <- function(data_beta) {
  cpg <- data_beta$cpg_beta$cpg_beta_df
  if (is.null(cpg)) return(NULL)
  cpg_ids <- rownames(cpg)
  if (is.null(cpg_ids)) return(NULL)

  mapping <- get_icr_mapping_for_qc()
  if (is.null(mapping)) return(NULL)
  mapping <- mapping[mapping$CpG_id %in% cpg_ids & !is.na(mapping$ICR_id), , drop = FALSE]
  if (nrow(mapping) == 0) return(NULL)

  cpg_counts <- as.data.frame(table(mapping$ICR_id), stringsAsFactors = FALSE)
  names(cpg_counts) <- c("ICR_id", "CpGs_in_CpG_matrix")

  icr <- data_beta$icr_beta$icr_beta_df
  if (!is.null(icr)) {
    icr_missing <- data.frame(
      ICR_id = rownames(icr),
      ICR_missing_fraction = rowMeans(is.na(as.matrix(icr))),
      row.names = NULL
    )
    cpg_counts <- merge(cpg_counts, icr_missing, by = "ICR_id", all.x = TRUE, sort = FALSE)
  }

  metadata <- tryCatch(
    add_metadata_to_imp_sites(cpg_counts$ICR_id, imp_type = "icr", db_flag = FALSE),
    error = function(e) NULL
  )
  if (!is.null(metadata)) {
    cpg_counts <- merge(
      cpg_counts,
      metadata[, intersect(c("icr_id", "icr_conf", "is_icr_zinc", "ZFP57", "ZFP445", "Nearest.Transcript"), colnames(metadata)), drop = FALSE],
      by.x = "ICR_id",
      by.y = "icr_id",
      all.x = TRUE,
      sort = FALSE
    )
  }

  cpg_counts
}

build_replicate_probe_qc <- function(data_beta) {
  probe_beta <- data_beta$filt_probe_beta$probe_beta_df
  if (is.null(probe_beta)) probe_beta <- data_beta$probe_beta$probe_beta_df
  if (is.null(probe_beta) || is.null(rownames(probe_beta))) return(NULL)

  probe_m <- as.matrix(probe_beta)
  storage.mode(probe_m) <- "numeric"
  cpg_key <- strip_probe_suffix(rownames(probe_m))
  replicated_keys <- names(table(cpg_key))[table(cpg_key) > 1]
  if (length(replicated_keys) == 0) return(NULL)

  out <- lapply(replicated_keys, function(key) {
    idx <- which(cpg_key == key)
    sub_m <- probe_m[idx, , drop = FALSE]
    mean_cor <- NA_real_
    min_cor <- NA_real_
    if (nrow(sub_m) > 1 && ncol(sub_m) > 1) {
      cor_mat <- suppressWarnings(stats::cor(t(sub_m), use = "pairwise.complete.obs"))
      cor_vals <- cor_mat[upper.tri(cor_mat)]
      cor_vals <- cor_vals[is.finite(cor_vals)]
      if (length(cor_vals) > 0) {
        mean_cor <- mean(cor_vals)
        min_cor <- min(cor_vals)
      }
    }
    data.frame(
      CpG = key,
      N_replicate_probes = length(idx),
      Mean_replicate_correlation = mean_cor,
      Min_replicate_correlation = min_cor,
      row.names = NULL
    )
  })

  do.call(rbind, out)
}

draw_tdhia_qc_plots <- function(beta_m,
                                plot_matrix,
                                level,
                                sample_metrics,
                                feature_metrics,
                                max_density_samples,
                                sample_outliers,
                                detection_qc,
                                retention_summary,
                                design_score_qc,
                                icr_coverage_qc,
                                replicate_probe_qc) {
  old_par <- graphics::par(no.readonly = TRUE)
  on.exit(graphics::par(old_par), add = TRUE)

  feature_label <- names(feature_metrics)[1]
  title_prefix <- paste0("TDHIA ", toupper(level), " QC")

  graphics::par(mfrow = c(2, 2))
  graphics::hist(
    sample_metrics$NA_fraction,
    breaks = 30,
    main = "Per-sample NA fraction",
    xlab = "Fraction NA"
  )
  graphics::hist(
    feature_metrics$NA_fraction,
    breaks = 30,
    main = paste("Per-", feature_label, " NA fraction", sep = ""),
    xlab = "Fraction NA"
  )
  graphics::hist(
    sample_metrics$Mean_beta,
    breaks = 30,
    main = "Mean beta per sample",
    xlab = "Mean beta"
  )
  graphics::hist(
    sample_metrics$SD_beta,
    breaks = 30,
    main = "SD beta per sample",
    xlab = "SD beta"
  )

  if (nrow(plot_matrix) == 0 || ncol(plot_matrix) == 0) {
    graphics::plot.new()
    graphics::title(main = paste(title_prefix, "plots unavailable: all values are NA"))
    return(invisible(NULL))
  }

  graphics::par(mfrow = c(1, 1))
  density_cols <- seq_len(min(ncol(plot_matrix), max_density_samples))
  density_cols <- density_cols[
    vapply(
      density_cols,
      function(j) length(unique(plot_matrix[, j][is.finite(plot_matrix[, j])])) > 1,
      logical(1)
    )
  ]

  if (length(density_cols) == 0) {
    graphics::plot.new()
    graphics::title(main = "Beta density overlay unavailable: samples have no variance")
  } else {
    density_list <- lapply(density_cols, function(j) stats::density(plot_matrix[, j]))
    xlim <- range(unlist(lapply(density_list, `[[`, "x")), finite = TRUE)
    ylim <- range(unlist(lapply(density_list, `[[`, "y")), finite = TRUE)

    graphics::plot(
      density_list[[1]],
      main = "Beta density overlay",
      xlab = "Beta",
      xlim = xlim,
      ylim = ylim
  )
    if (length(density_list) > 1) {
      for (j in 2:length(density_list)) {
        graphics::lines(density_list[[j]])
      }
    }
  }

  if (ncol(plot_matrix) > 1) {
    cor_mat <- stats::cor(plot_matrix, use = "pairwise.complete.obs")
    stats::heatmap(cor_mat, symm = TRUE, main = "Sample-sample correlation heatmap")
  } else {
    graphics::plot.new()
    graphics::title(main = "Sample-sample correlation requires at least 2 samples")
  }

  if (ncol(plot_matrix) >= 2 && nrow(plot_matrix) >= 2) {
    pc <- stats::prcomp(t(plot_matrix), center = TRUE, scale. = FALSE)
    graphics::par(mfrow = c(1, 2))

    if (ncol(pc$x) >= 2) {
      graphics::plot(
        pc$x[, 1],
        pc$x[, 2],
        pch = 19,
        main = "PCA: PC1 vs PC2",
        xlab = "PC1",
        ylab = "PC2"
      )
    } else {
      graphics::plot.new()
      graphics::title(main = "PCA: PC1 vs PC2 unavailable")
    }

    if (ncol(pc$x) >= 3) {
      graphics::plot(
        pc$x[, 1],
        pc$x[, 3],
        pch = 19,
        main = "PCA: PC1 vs PC3",
        xlab = "PC1",
        ylab = "PC3"
      )
    } else {
      graphics::plot.new()
      graphics::title(main = "PCA: PC1 vs PC3 requires at least 3 PCs")
    }
  } else {
    graphics::plot.new()
    graphics::title(main = "PCA requires at least 2 samples and 2 features")
  }

  draw_tdhia_extended_qc_plots(
    sample_outliers = sample_outliers,
    detection_qc = detection_qc,
    retention_summary = retention_summary,
    design_score_qc = design_score_qc,
    icr_coverage_qc = icr_coverage_qc,
    replicate_probe_qc = replicate_probe_qc
  )

  invisible(NULL)
}

draw_tdhia_extended_qc_plots <- function(sample_outliers,
                                         detection_qc,
                                         retention_summary,
                                         design_score_qc,
                                         icr_coverage_qc,
                                         replicate_probe_qc) {
  graphics::par(mfrow = c(2, 2))

  graphics::barplot(
    retention_summary$Features,
    names.arg = retention_summary$Matrix,
    las = 2,
    main = "Feature retention summary",
    ylab = "N features"
  )

  if (!is.null(detection_qc)) {
    graphics::hist(
      detection_qc$sample_metrics$Detection_fail_fraction,
      breaks = 30,
      main = "Detection failures by sample",
      xlab = paste0("Fraction p > ", detection_qc$threshold)
    )
    graphics::hist(
      detection_qc$probe_metrics$Detection_fail_fraction,
      breaks = 30,
      main = "Detection failures by probe",
      xlab = paste0("Fraction p > ", detection_qc$threshold)
    )
  } else {
    graphics::plot.new()
    graphics::title(main = "Detection p-value QC unavailable")
    graphics::plot.new()
    graphics::title(main = "Detection p-value QC unavailable")
  }

  graphics::barplot(
    table(sample_outliers$Any_outlier_flag),
    main = "Sample outlier flags",
    ylab = "N samples",
    xlab = "Any flag"
  )

  graphics::par(mfrow = c(2, 2))
  if (!is.null(design_score_qc)) {
    graphics::hist(
      design_score_qc$Design.Score,
      breaks = 30,
      main = "Probe design scores",
      xlab = "Design score"
    )
    graphics::boxplot(
      Design.Score ~ Retained,
      data = design_score_qc,
      main = "Design score by retention",
      xlab = "Retained after filtering",
      ylab = "Design score"
    )
  } else {
    graphics::plot.new()
    graphics::title(main = "Design score QC unavailable")
    graphics::plot.new()
    graphics::title(main = "Design score QC unavailable")
  }

  if (!is.null(icr_coverage_qc)) {
    graphics::hist(
      icr_coverage_qc$CpGs_in_CpG_matrix,
      breaks = 30,
      main = "CpG coverage per ICR",
      xlab = "CpGs in CpG matrix"
    )
    if ("ICR_missing_fraction" %in% colnames(icr_coverage_qc)) {
      graphics::hist(
        icr_coverage_qc$ICR_missing_fraction,
        breaks = 30,
        main = "ICR missingness",
        xlab = "Fraction missing"
      )
    } else {
      graphics::plot.new()
      graphics::title(main = "ICR missingness unavailable")
    }
  } else {
    graphics::plot.new()
    graphics::title(main = "ICR coverage QC unavailable")
    graphics::plot.new()
    graphics::title(main = "ICR coverage QC unavailable")
  }

  graphics::par(mfrow = c(1, 2))
  if (!is.null(replicate_probe_qc)) {
    graphics::hist(
      replicate_probe_qc$N_replicate_probes,
      breaks = 30,
      main = "Replicate probes per CpG",
      xlab = "N replicate probes"
    )
    graphics::hist(
      replicate_probe_qc$Mean_replicate_correlation,
      breaks = 30,
      main = "Replicate probe agreement",
      xlab = "Mean replicate correlation"
    )
  } else {
    graphics::plot.new()
    graphics::title(main = "Replicate probe QC unavailable")
    graphics::plot.new()
    graphics::title(main = "Replicate probe QC unavailable")
  }

  invisible(NULL)
}

abs_z_flag <- function(x, threshold) {
  z <- z_score(x)
  ifelse(is.na(z), FALSE, abs(z) > threshold)
}

lower_tail_z_flag <- function(x, threshold) {
  z <- z_score(x)
  ifelse(is.na(z), FALSE, z < -threshold)
}

z_score <- function(x) {
  x_sd <- stats::sd(x, na.rm = TRUE)
  if (is.na(x_sd) || x_sd == 0) return(rep(NA_real_, length(x)))
  (x - mean(x, na.rm = TRUE)) / x_sd
}

nrow_or_na <- function(x) {
  if (is.null(x)) return(NA_integer_)
  nrow(x)
}

ncol_or_na <- function(x) {
  if (is.null(x)) return(NA_integer_)
  ncol(x)
}

strip_probe_suffix <- function(x) {
  sub("_.*$", "", x)
}

get_icr_mapping_for_qc <- function() {
  if (requireNamespace("tdhia", quietly = TRUE) &&
      exists("mapping_cpg_icr_ids", envir = asNamespace("tdhia"))) {
    mapping <- get("mapping_cpg_icr_ids", envir = asNamespace("tdhia"))
    if (all(c("CpG_id", "ICR_id") %in% colnames(mapping))) return(mapping)
  }
  NULL
}
